name: Deploy a Railway

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  notificar-exito:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "GitHub Actions 🤖"
          SLACK_TITLE: "CI/CD exitoso"
          SLACK_MESSAGE: |
            El pipeline de CI/CD se ejecutó correctamente para:
            • Repo: ${{ github.repository }}
            • Commit: ${{ github.event.head_commit.message }}
            • Autor: ${{ github.event.head_commit.author.name }}
            🔗 Ver workflow: ${{ github.server_url }}/${{ github.repository }}/actions
          SLACK_COLOR: good


  notificar-error:
    if: failure()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "GitHub Actions 🤖"
          SLACK_TITLE: "Error en CI/CD"
          SLACK_MESSAGE: |
            El pipeline de CI/CD se ejecutó correctamente para:
            • Repo: ${{ github.repository }}
            • Commit: ${{ github.event.head_commit.message }}
            • Autor: ${{ github.event.head_commit.author.name }}
            🔗 Ver workflow: ${{ github.server_url }}/${{ github.repository }}/actions
          SLACK_COLOR: danger