name: Deploy a Railway

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  notificar-exito:
    if: success()
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Crear issue por deploy exitoso
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Deploy a Railway completado con éxito"
          content-filepath: ./.github/success-message.md
          labels: success, deploy

  notificar-error:
    if: failure()
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Crear issue por fallo en deploy
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Fallo en el Deploy"
          content-filepath: ./.github/failure-message.md
          labels: bug, deploy 